<?php

declare(strict_types=1);

namespace App\Domains\VoucherConfiguration\Enums;

use App\Http\Traits\PrepareEnumDataMethods;

enum VouchersTypes: int
{
    use PrepareEnumDataMethods;

    case BIRTHDAY_RESTRICTED_BY_MEMBER_PERCENTAGE_VOUCHER = 1;
    case BIRTHDAY_RESTRICTED_BY_MEMBER_FLAT_VOUCHER = 2;
    case TIER_RESTRICTED_BY_ALL_PERCENTAGE_VOUCHER = 3;
    case TIER_RESTRICTED_BY_ALL_FLAT_VOUCHER = 4;
    case TIER_RESTRICTED_BY_MEMBER_PERCENTAGE_VOUCHER = 5;
    case TIER_RESTRICTED_BY_MEMBER_FLAT_VOUCHER = 6;
    case TIER_RESTRICTED_BY_NON_MEMBER_PERCENTAGE_VOUCHER = 7;
    case TIER_RESTRICTED_BY_NON_MEMBER_FLAT_VOUCHER = 8;
    case MULTIPLE_RESTRICTED_BY_ALL_PERCENTAGE_VOUCHER = 9;
    case MULTIPLE_RESTRICTED_BY_ALL_FLAT_VOUCHER = 10;
    case MULTIPLE_RESTRICTED_BY_MEMBER_PERCENTAGE_VOUCHER = 11;
    case MULTIPLE_RESTRICTED_BY_MEMBER_FLAT_VOUCHER = 12;
    case MULTIPLE_RESTRICTED_BY_NON_MEMBER_PERCENTAGE_VOUCHER = 13;
    case MULTIPLE_RESTRICTED_BY_NON_MEMBER_FLAT_VOUCHER = 14;
    case WELCOME_MEMBER_RESTRICTED_BY_MEMBER_PERCENTAGE_VOUCHER = 15;
    case WELCOME_MEMBER_RESTRICTED_BY_MEMBER_FLAT_VOUCHER = 16;
    case LOYALTY_POINT_RESTRICTED_BY_MEMBER_PERCENTAGE_VOUCHER = 17;
    case LOYALTY_POINT_RESTRICTED_BY_MEMBER_FLAT_VOUCHER = 18;
}
