<?php

declare(strict_types=1);

namespace App\Domains\Common\Enums;

use App\Http\Traits\PrepareEnumDataMethods;

enum WebhookUrls: int
{
    use PrepareEnumDataMethods;

    case PRODUCT_CREATE = 1;
    case INVENTORY_CREATE = 9;
    case INVENTORY_CREATE_VARIANCE = 10;
    case PRODUCT_UPDATES = 12;
    case INVENTORY_UPDATES = 20;
    case INVENTORY_UPDATES_VARIANCE = 21;
    case ONLINE_SALE_CHARGE_CREATE = 22;
    case ONLINE_SALE_CHARGE_UPDATES = 23;
    case BANNER_CREATE = 24;
    case BANNER_UPDATES = 25;
    case PRODUCT_DELETE = 26;
    case ORDER_STATUS_UPDATE = 27;
    case ONLINE_SALE_CHARGE_DELETE = 28;
    case DREAM_PRICE_UPDATES = 29;
    case PRODUCT_COLLECTION_UPDATES = 30;
    case PRODUCT_COLLECTION_DELETE = 31;
    case ORDER_STATUS_ACCEPTED = 32;
    case ORDER_STATUS_READY_FOR_PICKUP = 33;
    case ORDER_STATUS_DELIVERED = 34;
    case ORDER_STATUS_CANCELLED = 35;
    case ORDER_STATUS_DECLINED = 36;
    case PRODUCT_VARIANCE_CREATE = 37;
    case PRODUCT_VARIANCE_UPDATE = 38;
    case PRODUCT_VARIANCE_DELETE = 39;
    case CATEGORY_CREATE = 40;
    case CATEGORY_UPDATE = 41;
    case UPLOAD_IMAGE = 42;
    case BRAND_CREATE = 43;
    case BRAND_UPDATE = 44;
    case COLOR_CREATE = 45;
    case COLOR_UPDATE = 46;
    case SIZE_CREATE = 47;
    case SIZE_UPDATE = 48;
    case MEMBER_CREATE = 49;
    case MEMBER_UPDATE = 50;
    case MEMBER_ADDRESS_CREATE = 51;
    case MEMBER_ADDRESS_UPDATE = 52;
    case MEMBER_ADDRESS_DELETE = 53;
    case MEMBER_GROUP_UPDATE = 54;
    case DREAM_PRICE_CREATE = 55;
    case MEMBER_DELETE = 56;
    case MEMBER_MERGE = 57;
    case PRODUCT_MERGE = 58;
    case MEMBERSHIP_CREATE = 59;
    case MEMBERSHIP_UPDATE = 60;
    case VOUCHER_CONFIGURATION_CREATE = 61;
    case VOUCHER_CONFIGURATION_UPDATE = 62;
    case LOYALTY_CAMPAIGN_CREATE = 63;
    case LOYALTY_CAMPAIGN_UPDATE = 64;
    case VOUCHER_CREATE = 65;
    case VOUCHER_UPDATE = 66;
    case ATTRIBUTE_CREATE = 67;
    case ATTRIBUTE_UPDATE = 68;
    case ATTRIBUTE_DELETE = 69;
    case PAYMENT_TYPE_CREATE = 70;
    case PAYMENT_TYPE_UPDATE = 71;
    case CATEGORY_UNAVAILABLE = 72;
    case MASTER_PRODUCT_CREATE = 73;
    case MASTER_PRODUCT_UPDATE = 74;
    case PRODUCT_UNAVAILABLE = 75;
    case PRODUCT_COLLECTION_CREATE_UPDATE = 76;
    case PRODUCT_COLLECTION_UNAVAILABLE = 77;
    case ONLINE_SALES_CHARGES_UNAVAILABLE = 78;
    case PROMOTION_CREATE = 79;
    case PROMOTION_UPDATE = 80;
    case PROMOTION_UNAVAILABLE = 81;
    case DREAM_PRICE_UNAVAILABLE = 82;
    case LOYALTY_POINT_UPDATES_CREATE = 83;
    case LOYALTY_POINT_UPDATES_UPDATE = 84;
    case LOYALTY_POINT_CREATE = 85;
    case LOYALTY_POINT_UPDATE = 86;
    case SHIPPING_ZONE_CREATE = 87;
    case SHIPPING_ZONE_UPDATE = 88;
    case COUNTRY_CREATE = 89;
    case COUNTRY_UPDATES = 90;
    case STATE_CREATE = 91;
    case STATE_UPDATES = 92;
    case DYNAMIC_MENU_CREATE = 93;
    case DYNAMIC_MENU_UPDATE = 94;
    case ORDER_ADDRESS_UPDATE = 95;
    case TRIGGER_SALE_CHANNEL_SYNC = 96;
    case VOUCHER_CONFIGURATION_UNAVAILABLE = 97;
    case PAYMENT_TYPE_UNAVAILABLE = 98;
    case SALE_RETURN_REASON_SYNC = 99;
    case CITY_CREATE = 100;
    case CITY_UPDATES = 101;
}
